steps:
  - label: ":construction_worker: Build"
    command: echo "Build the rocket"
    key: build

  - label: ":white_check_mark: Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build
    if: build.env("BUILDKITE_GITHUB_PULL_REQUEST_STACK_POSITION") == "1"

  - label: ":rocket: Deploy"
    command: |
      echo "Launch the rocket"
      cat .buildkite/annotation.md | buildkite-agent annotate --style "success"
    key: deploy
    if: build.env("BUILDKITE_GITHUB_PULL_REQUEST_STACK_POSITION") == "2"
